services:
  - type: web
    name: bebez-office-hp
    env: node
    plan: free
    buildCommand: npm install
    staticPublishPath: public
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLAUDE_API_KEY
        sync: false
